# Generated by Django 4.1.1 on 2023-04-21 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tweet_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.TextField()),
                ('positive_tweets', models.IntegerField(default=0)),
                ('negative_tweets', models.IntegerField(default=0)),
            ],
        ),
    ]
