# Generated by Django 4.1.1 on 2023-04-25 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_tweet_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='username',
            field=models.CharField(default='harry', max_length=255),
        ),
    ]
